"""Generated by h01_e_b3_profile_export.py from b3-sk035-ca-decay-sweep53.json (sha256 52f85ac9f1e88d0a8051916932f2b2873ef26aaf241bf6b88441071f40cf92e1).

Pinned physical densities (S/cm2), capacitance (uF/cm2), decay (ms); phase controls
and passive scalars for registration. Do not edit by hand."""

E_B3_EXPERIMENTAL = (('soma',
  1.0,
  0.0004214870638616726,
  (('Im', 0.0003009224287506406),
   ('Ih', 9.994138594205759e-05),
   ('NaTs', 2.6406641498523276),
   ('Nap', 0.00027834876277937903),
   ('K_P', 0.0002294964697530516),
   ('K_T', 1.1414657313560486e-08),
   ('SK', 0.001049516063519434),
   ('Kv3_1', 0.3687667632247488),
   ('Ca_HVA', 0.0009983602924910323),
   ('Ca_LVA', 0.00824261450980065)),
  (494.01955262344603, 0.0008762096311710155)),
 ('axon', 1.0, 0.00028089935810004884, (('NaTs', 3.814),), None),
 ('dend', 2.3031548608821226, 3.626643561453563e-05, (('Ih', 9.994138594205759e-05),), None),
 ('apic', 2.3031548608821226, 4.119170292066434e-05, (('Ih', 9.994138594205759e-05),), None))

E_B3_EXPERIMENTAL_CONTROLS = {'Kv3_1': {'m_close': 0.9}, 'NaTs': {'h_recovery': 1.0, 'm_open': 2.0}}

E_B3_EXPERIMENTAL_INPUT = {'added_bias_na': -0.003711858945210089, 'description': 'command plus recorded bias'}

E_B3_EXPERIMENTAL_SOURCE = {'candidate_json': {'file': 'b3-sk035-ca-decay.candidate.json',
                    'sha256': 'e4825c83bdc7980a469b5501b2a54c68e680f1cb52a2055d36bcf4fc7b70e564',
                    'values': {'calcium_decay_factor': 1.0,
                               'cvode_atol': 1e-10,
                               'distribute_ih': True,
                               'ih_density_factor': 75.0,
                               'insert_density': ['NaTs:axon:3.814'],
                               'kv3_closing_factor': 0.9,
                               'leak_reversal_shift_mv': -4.0,
                               'nseg_factor': 9,
                               'record_soma_currents': False,
                               'regional_density': ['SK:soma:0.35'],
                               'sodium_density_factor': 0.9,
                               'sodium_opening_factor': 2.0,
                               'sodium_recovery_factor': 1.0,
                               'stop_ms': 2100.0}},
 'fit_sha256': '2ceca2317ccbd586adde4b1e72507ad4bdf2fc10fc26ad4b281484324dd5f0c3',
 'model_id': 626170538,
 'specimen_id': 541563728}

E_B3_EXPERIMENTAL_AXIAL_OHM_CM = 94.62299222737664
E_B3_EXPERIMENTAL_REVERSAL_MV = -87.97993469238281
E_B3_EXPERIMENTAL_INITIAL_MV = -83.97993469238281
