"""Emit the E B3 finalist as an ``_h01_ei_parameters`` region tuple from the NEURON report.

Reads ``applied_genome``, ``applied_passive_parameters`` and the phase-control
flags of ``h01-e-usable/b3-sk035-ca-decay-sweep53.json`` and writes a Python
literal file. Registration into ``_h01_ei_parameters`` happens after the
registry re-key merges; this file is the generated source for that step.
"""

import argparse
import hashlib
import json
import pprint
from pathlib import Path

REGIONS = ("soma", "axon", "dend", "apic")
CHANNEL_ORDER = ("Im", "Ih", "NaTs", "Nap", "K_P", "K_T", "SK", "Kv3_1", "Ca_HVA", "Ca_LVA")
DEFAULT_REPORT = "h01-e-usable/b3-sk035-ca-decay-sweep53.json"
DEFAULT_OUTPUT = "h01-e-b3-experimental-profile.py"


def region_tuple(report, region):
    """One ``(family, cm, leak, channels, calcium)`` row from the applied genome and passive block."""
    rows = [row for row in report["applied_genome"] if row["section"] == region]
    passive = report["applied_passive_parameters"][0]
    cm = next(row["cm"] for row in passive["cm"] if row["section"] == region)
    leak = next(row["value"] for row in rows if row["name"] == "g_pas")
    densities = {row["name"][len("gbar_"):]: row["value"] for row in rows if row["name"].startswith("gbar_")}
    unknown = set(densities)-set(CHANNEL_ORDER)
    if unknown:
        raise ValueError(f"Unknown channel density in {region}: {sorted(unknown)}")
    channels = tuple((name, densities[name]) for name in CHANNEL_ORDER if name in densities)
    calcium = None
    if any(row["mechanism"] == "CaDynamics" for row in rows):
        calcium = (next(row["value"] for row in rows if row["name"] == "decay_CaDynamics"),
                   next(row["value"] for row in rows if row["name"] == "gamma_CaDynamics"))
    return (region, cm, leak, channels, calcium)


def profile_from_report(report):
    """Region tuples plus the scalars and phase controls a profile registration needs."""
    passive = report["applied_passive_parameters"][0]
    return {"regions": tuple(region_tuple(report, region) for region in REGIONS),
            "axial_ohm_cm": passive["ra"], "reversal_mv": passive["e_pas"], "initial_mv": report["initial_mv"],
            "controls": {"NaTs": {"m_open": report["sodium_opening_factor"],
                                  "h_recovery": report["sodium_recovery_factor"]},
                         "Kv3_1": {"m_close": report["kv3_closing_factor"]}},
            "input": {"description": report["input"], "added_bias_na": report["added_bias_na"]},
            "source": {"model_id": report["model_id"], "specimen_id": report["specimen_id"],
                       "fit_sha256": report["fit_sha256"], "candidate_json": report["candidate_json"]}}


def render(profile, report_name, report_sha256):
    """Python source text holding ``E_B3_EXPERIMENTAL`` and its companions."""
    header = ('"""Generated by h01_e_b3_profile_export.py from '+report_name+' (sha256 '+report_sha256+').\n\n'
              'Pinned physical densities (S/cm2), capacitance (uF/cm2), decay (ms); phase controls\n'
              'and passive scalars for registration. Do not edit by hand."""\n\n')
    body = "".join(f"{name} = {pprint.pformat(profile[key], width=100)}\n\n" for name, key in (
        ("E_B3_EXPERIMENTAL", "regions"), ("E_B3_EXPERIMENTAL_CONTROLS", "controls"),
        ("E_B3_EXPERIMENTAL_INPUT", "input"), ("E_B3_EXPERIMENTAL_SOURCE", "source")))
    scalars = (f"E_B3_EXPERIMENTAL_AXIAL_OHM_CM = {profile['axial_ohm_cm']!r}\n"
               f"E_B3_EXPERIMENTAL_REVERSAL_MV = {profile['reversal_mv']!r}\n"
               f"E_B3_EXPERIMENTAL_INITIAL_MV = {profile['initial_mv']!r}\n")
    return header+body+scalars


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=Path(__file__).parent/DEFAULT_REPORT)
    parser.add_argument("--output", type=Path, default=Path(__file__).parent/DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    report = json.loads(args.report.read_text())
    text = render(profile_from_report(report), args.report.name, hashlib.sha256(args.report.read_bytes()).hexdigest())
    args.output.write_text(text)
    print(json.dumps({"output": str(args.output), "regions": [row[0] for row in profile_from_report(report)["regions"]]}))


if __name__ == "__main__":
    main()
